GenCC:
  download_url: https://search.thegencc.org/download/action/submissions-export-tsv
  download_dir: /home/ubuntu/tony/data/gencc_download
  raw_filename: submissions-export-tsv
  tsv_filename: gencc_submisison.tsv

Key:
  - gene_curie
  - gene_symbol
  - disease_curie
  - disease_title
  - disease_original_curie
  - disease_original_title
  - classification_curie
  - classification_title
  - submitted_as_date
  - submitted_as_public_report_url
  - submitted_as_notes
  - submitted_as_pmids
  - submitted_as_assertion_criteria_url
  - submitted_run_date