panel_header:
  - panel_id
  - hash_id
  - name
  - disease_group
  - status
  - version
  - version_created
  - relevant_disorders
  - panel_types
  - gene_name
  - number_of_genes
  - number_of_strs
  - number_of_regions