panelApp: 
  API_URL: https://panelapp.genomicsengland.co.uk/api/v1

Key:
  - entity_name
  - gene_data:
    - gene_name
    - omim_gene
    - alias
    - alias_name
  - entity_type
  - panel:
    - name
    - disease_group
    - disease_sub_group
    - version_created
    - relevant_disorders
    - types
  - phenotypes
  - confidence_level
  - mode_of_inheritance
  - mode_of_pathogenicity
  - penetrance
  - evidence
  - publications